// ╔══════════════════════════════════════════════════════════════════╗
// ║  CONSTANTS & CONFIG — Data-only module for Resume Builder       ║
// ║  Ported from resumeforge.jsx §1 Constants & Config              ║
// ╚══════════════════════════════════════════════════════════════════╝

export const INDUSTRY_KEYWORDS = {
  "Business Coaching & Consulting": ["Client Engagement", "Strategic Planning", "Scaling", "Business Transformation", "KPIs", "Stakeholder Management", "Advisory", "Executive Coaching", "Organizational Development"],
  "Leadership & Executive Development": ["Visionary Leadership", "Team Building", "Executive Coaching", "Organizational Culture", "Change Management", "Succession Planning", "C-Suite", "Vision Setting", "Thought Leadership"],
  "Entrepreneurship & Startups": ["Startup", "Venture", "Bootstrapping", "Go-to-Market", "Fundraising", "MVP", "Business Model", "Scaling", "Growth Stage", "Serial Entrepreneur"],
  "Sales & Revenue Growth": ["Revenue Growth", "Pipeline", "CRM", "High Ticket Sales", "B2B", "Account Management", "Negotiation", "Closing", "Deal Flow", "Enterprise Sales"],
  "Training & Development": ["Upskilling", "Workshops", "Masterclass", "Curriculum Design", "Corporate Training", "E-Learning", "Facilitation", "Coaching Program", "Leadership Development"],
  "Marketing & Personal Branding": ["Personal Branding", "Content Strategy", "Digital Marketing", "SEO", "Social Media", "Influence", "Brand Building", "Thought Leadership", "Authority"],
  "Operations & Strategy": ["Process Optimization", "Strategic Planning", "Business Operations", "Efficiency", "Lean", "SOP", "Vendor Management", "Systems", "Scalability"],
  "Finance & Investment": ["Financial Modeling", "Forecasting", "P&L", "Risk Analysis", "Compliance", "Budgeting", "Valuation", "Capital", "Revenue Model"],
  "Technology & Engineering": ["Agile", "CI/CD", "Microservices", "REST API", "Cloud", "DevOps", "System Design", "TDD", "Scalability", "Architecture"],
  "Product Management": ["Roadmap", "OKRs", "User Research", "A/B Testing", "Go-to-Market", "Sprint Planning", "KPIs", "Cross-functional", "Product Strategy"],
  "Data & Analytics": ["Machine Learning", "Python", "SQL", "Data Pipeline", "Feature Engineering", "Deep Learning", "NLP", "Statistical Modeling", "Analytics"],
  "Design & Creative": ["UI/UX", "Figma", "Design Systems", "Prototyping", "Wireframing", "Accessibility", "Visual Design", "User Experience"],
  "Human Resources & Talent": ["Talent Acquisition", "HRIS", "Onboarding", "Performance Management", "Diversity & Inclusion", "Recruitment", "Talent Strategy"],
  "Healthcare & Life Sciences": ["Clinical", "Medical", "Pharmaceutical", "Healthcare", "Life Sciences", "Biotech", "FDA", "Regulatory", "Patient Care"],
  "Legal & Compliance": ["Legal", "Compliance", "Risk", "Regulatory", "Contract", "Litigation", "Intellectual Property", "Privacy", "Governance"],
  "Education & Academia": ["Teaching", "Academic", "Research", "University", "Curriculum", "Student", "Faculty", "Publishing", "Scholarship"],
  "Real Estate & Construction": ["Real Estate", "Construction", "Development", "Property", "Commercial", "Residential", "Architecture", "Infrastructure"],
  "Hospitality & Tourism": ["Hospitality", "Tourism", "Hotel", "Restaurant", "Event Management", "Customer Experience", "Travel", "Venue"],
  "Non-Profit & Social Impact": ["Non-Profit", "Social Impact", "Community", "Charity", "Fundraising", "Advocacy", "Grant", "Mission", "Impact"],
};

export const ROLE_MAP = {
  "coach": ["Business Coaching & Consulting", "Leadership & Executive Development", "Training & Development"],
  "coaching": ["Business Coaching & Consulting", "Leadership & Executive Development"],
  "consultant": ["Business Coaching & Consulting", "Operations & Strategy"],
  "consulting": ["Business Coaching & Consulting", "Operations & Strategy"],
  "speaker": ["Leadership & Executive Development", "Training & Development", "Marketing & Personal Branding"],
  "founder": ["Entrepreneurship & Startups", "Operations & Strategy"],
  "entrepreneur": ["Entrepreneurship & Startups"],
  "author": ["Leadership & Executive Development", "Training & Development", "Marketing & Personal Branding"],
  "trainer": ["Training & Development"],
  "mentor": ["Leadership & Executive Development", "Training & Development"],
  "ceo": ["Leadership & Executive Development", "Operations & Strategy"],
  "cxo": ["Leadership & Executive Development"],
  "director": ["Leadership & Executive Development", "Operations & Strategy"],
  "executive": ["Leadership & Executive Development"],
  "branding": ["Marketing & Personal Branding"],
  "personal brand": ["Marketing & Personal Branding"],
  "thought leader": ["Leadership & Executive Development", "Marketing & Personal Branding"],
  "leadership": ["Leadership & Executive Development"],
  "organizational": ["Operations & Strategy", "Leadership & Executive Development"],
  "change management": ["Operations & Strategy", "Leadership & Executive Development"],
  "transformation": ["Business Coaching & Consulting", "Operations & Strategy"],
  "sales": ["Sales & Revenue Growth"],
  "revenue": ["Sales & Revenue Growth"],
  "account executive": ["Sales & Revenue Growth"],
  "engineer": ["Technology & Engineering"],
  "developer": ["Technology & Engineering"],
  "devops": ["Technology & Engineering", "Operations & Strategy"],
  "architect": ["Technology & Engineering"],
  "sre": ["Technology & Engineering"],
  "frontend": ["Technology & Engineering", "Design & Creative"],
  "backend": ["Technology & Engineering"],
  "data scientist": ["Data & Analytics"],
  "data analyst": ["Data & Analytics"],
  "analytics": ["Data & Analytics"],
  "product manager": ["Product Management"],
  "designer": ["Design & Creative"],
  "ux": ["Design & Creative"],
  "ui": ["Design & Creative"],
  "marketing": ["Marketing & Personal Branding"],
  "growth": ["Sales & Revenue Growth", "Marketing & Personal Branding"],
  "finance": ["Finance & Investment"],
  "cfo": ["Finance & Investment", "Leadership & Executive Development"],
  "accountant": ["Finance & Investment"],
  "hr": ["Human Resources & Talent"],
  "recruiter": ["Human Resources & Talent"],
  "talent": ["Human Resources & Talent"],
  "philanthrop": ["Non-Profit & Social Impact", "Leadership & Executive Development"],
  "nonprofit": ["Non-Profit & Social Impact"],
  "program manager": ["Product Management", "Operations & Strategy"],
};

export const ACTION_VERBS = ["Spearheaded", "Orchestrated", "Engineered", "Transformed", "Architected", "Championed", "Pioneered", "Accelerated", "Streamlined", "Delivered", "Optimized", "Scaled", "Led", "Drove", "Implemented", "Designed", "Built", "Launched", "Reduced", "Cultivated", "Fostered", "Established", "Elevated"];

export const RECOMMENDED_CERTS = {
  "Business Coaching & Consulting": ["ICF Associate Certified Coach (ACC)", "WABC Certified Business Coach (CBC)", "Certified Management Consultant (CMC)", "Marshall Goldsmith Stakeholder Centered Coaching", "EOS Implementer Certification"],
  "Leadership & Executive Development": ["ICF Professional Certified Coach (PCC)", "Center for Creative Leadership (CCL)", "Hogan Assessment Certified", "DISC Certified Facilitator", "Korn Ferry Leadership Architect Certification"],
  "Entrepreneurship & Startups": ["Lean Startup Methodology (Eric Ries)", "Y Combinator Startup School", "Certified Innovation Professional (CInP)", "Scaling Up (Verne Harnish)", "EOS Implementer"],
  "Sales & Revenue Growth": ["Certified Sales Professional (CSP)", "HubSpot Inbound Sales", "Sandler Sales Certification", "SPIN Selling Practitioner", "Challenger Sale Certified"],
  "Training & Development": ["ATD Certified Professional in Talent Development (CPTD)", "Certified Professional in Training Management (CPTM)", "Kirkpatrick Four Levels Certification", "DDI Facilitator Certification", "SHRM Senior Certified Professional (SHRM-SCP)"],
  "Marketing & Personal Branding": ["Google Digital Marketing Certificate", "HubSpot Content Marketing Certification", "Meta Certified Marketing Science Professional", "Certified Brand Strategist (CBS)", "StoryBrand Certified Guide"],
  "Operations & Strategy": ["Project Management Professional (PMP)", "Lean Six Sigma Black Belt (CSSBB)", "Certified Supply Chain Professional (CSCP)", "Prosci Change Management Certification", "Balanced Scorecard Professional (BSP)"],
  "Finance & Investment": ["CFA (Chartered Financial Analyst)", "CPA (Certified Public Accountant)", "FMVA (Financial Modeling & Valuation Analyst)", "FRM (Financial Risk Manager)", "CFP (Certified Financial Planner)"],
  "Technology & Engineering": ["AWS Solutions Architect", "Google Cloud Professional", "Certified Kubernetes Administrator", "Terraform Associate", "Azure Solutions Architect Expert"],
  "Product Management": ["Certified Scrum Product Owner (CSPO)", "Product School Product Manager Certificate", "Pragmatic Institute Certified", "SAFe Product Owner/Manager", "AIPMM Certified Product Manager"],
  "Data & Analytics": ["Google Data Analytics Professional Certificate", "AWS Certified Data Analytics", "Tableau Desktop Specialist", "Microsoft Certified: Data Analyst Associate", "Databricks Certified Data Engineer"],
  "Design & Creative": ["Google UX Design Certificate", "Nielsen Norman Group UX Certification", "Adobe Certified Expert", "Certified Usability Analyst (CUA)", "Interaction Design Foundation Certification"],
  "Human Resources & Talent": ["SHRM-CP/SHRM-SCP", "PHR/SPHR (HRCI)", "Certified Talent Acquisition Professional", "WorldatWork Certified Compensation Professional", "ATD Talent Development Certification"],
  "Healthcare & Life Sciences": ["Certified Healthcare Leader (CHL)", "Lean Six Sigma Healthcare", "CPHQ (Certified Professional in Healthcare Quality)", "PMP Healthcare", "FACHE (Fellow ACHE)"],
  "Non-Profit & Social Impact": ["Certified Fund Raising Executive (CFRE)", "Nonprofit Management Certificate", "Grant Professional Certified (GPC)", "Certified Association Executive (CAE)", "Social Enterprise Certificate"],
};

export const BULLET_TIPS = {
  "Business Coaching & Consulting": ["Mention number of clients coached or organizations transformed", "Show revenue impact: 'Helped clients achieve $X revenue growth'", "Include frameworks used: Scaling Up, EOS, OKRs", "Quantify team sizes coached or workshops delivered", "Reference industry breadth: '125+ business segments'"],
  "Leadership & Executive Development": ["Quantify leaders developed: 'Mentored 50+ C-suite executives'", "Show organizational impact: culture change, retention improvement", "Mention succession planning outcomes", "Reference assessment tools used: Hogan, DISC, StrengthsFinder", "Include program scale: workshops, cohorts, participants"],
  "Entrepreneurship & Startups": ["Lead with company outcomes: revenue, growth rate, funding raised", "Mention team size built and managed", "Show market impact: users, customers, geographic reach", "Include exit outcomes or scaling milestones", "Reference ecosystem contributions: mentoring, advisory boards"],
  "Sales & Revenue Growth": ["Always lead with revenue numbers: '$X in annual revenue'", "Show deal sizes and pipeline metrics", "Mention client acquisition and retention rates", "Quantify team quotas exceeded: '140% of target'", "Reference CRM tools and sales methodologies used"],
  "Training & Development": ["Show training scale: participants, sessions, locations", "Quantify learning outcomes: completion rates, skill improvements", "Mention content formats: masterclasses, workshops, e-learning", "Reference curriculum design and delivery methodology", "Include satisfaction scores or NPS for programs"],
  "Marketing & Personal Branding": ["Quantify audience reach: followers, impressions, engagement", "Show conversion metrics: leads generated, cost per acquisition", "Mention platforms and channels managed", "Reference brand authority metrics: speaking invitations, media features", "Include content output: articles, videos, podcast episodes"],
  "Operations & Strategy": ["Show process improvement metrics: efficiency gains, cost reduction", "Quantify teams and budgets managed", "Mention frameworks: Lean, Six Sigma, Agile, EOS", "Reference strategic planning outcomes: market share, growth", "Include operational scale: locations, headcount, revenue under management"],
};

export const TEMPLATES = {
  faang: { name: "Google / Big Tech", desc: "The X-Y-Z format Laszlo Bock endorses. Clean single-column, ATS-first, impact-per-line. Used by Google, Meta, Amazon, Apple recruiters.", accent: "#1e40af", headerStyle: "topBar", font: "'Segoe UI', sans-serif" },
  mbb: { name: "McKinsey / MBB", desc: "MECE structure. Centered serif header, leadership-first ordering. McKinsey, BCG, Bain hiring partners expect this exact format.", accent: "#9b8ec4", headerStyle: "centered", font: "Georgia, serif" },
  finance: { name: "Goldman / Wall Street", desc: "Ultra-dense, no-frills. Max content per page. Goldman, JPMorgan, Morgan Stanley — every pixel earns its place.", accent: "#7bab8e", headerStyle: "minimal", font: "'Helvetica Neue', Helvetica, Arial, sans-serif" },
  executive: { name: "C-Suite / Board", desc: "Narrative-driven for CEOs, VPs, Directors. Sidebar accent bar, reverse-text section headers. Board-ready gravitas.", accent: "#1a365d", headerStyle: "sidebar", font: "Cambria, Georgia, serif" },
  creative: { name: "Startup / Founder", desc: "For founders, coaches, speakers. Personal brand header, bold accent lines. Y Combinator and VC-facing.", accent: "#c97b7b", headerStyle: "hero", font: "'Inter', 'Segoe UI', sans-serif" },
  product: { name: "Product / Strategy", desc: "Optimized for PMs at Stripe, Airbnb, Spotify. Gradient section dividers, tag-based skills. User impact first.", accent: "#2563eb", headerStyle: "modern", font: "-apple-system, 'Segoe UI', sans-serif" },
};

export const TEMPLATE_META = {
  faang: { badge: "#1 Used", tags: ["Google", "Meta", "Amazon", "Apple", "Microsoft"], checks: ["Laszlo Bock's X-Y-Z bullet format", "100% ATS parse rate (tested)", "Single-column, no graphics", "Calibri/Segoe UI at 11pt"] },
  mbb: { badge: "Elite", tags: ["McKinsey", "BCG", "Bain", "Deloitte", "Big4"], checks: ["MECE-structured sections", "Leadership before skills", "One page unless 15+ years", "Georgia serif — prestige signal"] },
  finance: { badge: null, tags: ["Goldman Sachs", "JPMorgan", "Morgan Stanley", "PE/VC"], checks: ["Dense layout — 0.5\" margins", "Garamond/Helvetica — no decoration", "Education prominent if <5yr", "Every bullet has a dollar figure"] },
  executive: { badge: "Senior", tags: ["CEO", "VP", "Director", "C-Suite", "Board"], checks: ["Narrative-driven summary section", "Reverse-text section bars", "P&L and org impact front-loaded", "2 pages acceptable at this level"] },
  creative: { badge: null, tags: ["Startup", "Founder", "YC", "Coach", "Speaker"], checks: ["Bold personal brand header", "Accent-line section dividers", "Startup metrics (MRR, ARR, users)", "Funding & scale achievements first"] },
  product: { badge: null, tags: ["Stripe", "Airbnb", "Spotify", "PM", "Growth"], checks: ["Gradient section dividers", "OKR/KPI-driven bullets", "User impact metrics first", "Cross-functional leadership signals"] },
};

export const SOFT_SIGNAL_OPTIONS = [
  "High Autonomy", "Crisis Management", "Cross-Team Influence", "Mentorship & Coaching",
  "Ambiguity Navigation", "Zero-to-One Builder", "Scale Operator", "Political Navigation",
  "Data-Driven Decision Making", "Customer Obsession", "Rapid Prototyping", "Regulatory Compliance",
  "Founder Mentality", "Enterprise Rigor", "Creative Problem Solving", "Stakeholder Diplomacy",
  "Remote Leadership", "Turnaround Specialist", "Culture Builder", "Technical Depth",
];

export const COMPANY_CULTURE_PROFILES = {
  "chaotic-startup": { signals: ["fast-paced", "wear many hats", "scrappy", "ambiguous", "startup", "seed", "series a", "founding", "greenfield", "0 to 1", "zero to one", "move fast", "break things"], prioritize: ["Zero-to-One Builder", "High Autonomy", "Rapid Prototyping", "Ambiguity Navigation", "Founder Mentality", "Creative Problem Solving"] },
  "scale-up": { signals: ["series b", "series c", "hypergrowth", "scaling", "rapid growth", "doubling", "tripling", "expanding", "growing team"], prioritize: ["Scale Operator", "Cross-Team Influence", "Data-Driven Decision Making", "Remote Leadership", "Culture Builder", "Mentorship & Coaching"] },
  "big-tech": { signals: ["faang", "google", "meta", "amazon", "apple", "microsoft", "at scale", "millions of users", "distributed systems", "large-scale"], prioritize: ["Technical Depth", "Data-Driven Decision Making", "Cross-Team Influence", "Scale Operator", "Customer Obsession", "Enterprise Rigor"] },
  "enterprise": { signals: ["fortune 500", "enterprise", "compliance", "governance", "regulated", "banking", "insurance", "government", "procurement", "waterfall"], prioritize: ["Enterprise Rigor", "Regulatory Compliance", "Stakeholder Diplomacy", "Political Navigation", "Data-Driven Decision Making", "Scale Operator"] },
  "consulting": { signals: ["consulting", "advisory", "client", "engagement", "deliverable", "framework", "methodology", "mckinsey", "bcg", "bain", "deloitte", "pwc"], prioritize: ["Stakeholder Diplomacy", "Cross-Team Influence", "Data-Driven Decision Making", "Political Navigation", "Mentorship & Coaching", "Creative Problem Solving"] },
  "mission-driven": { signals: ["mission", "impact", "non-profit", "social", "community", "purpose", "sustainability", "climate", "health", "education"], prioritize: ["Culture Builder", "Mentorship & Coaching", "Creative Problem Solving", "Customer Obsession", "High Autonomy", "Stakeholder Diplomacy"] },
};

export const LEARNING_PATHS = {
  "python": { name: "Python", timeframe: "4-6 weeks", resource: "Google Python Certificate", credibility: "Google Career Certificates" },
  "sql": { name: "SQL", timeframe: "2-3 weeks", resource: "Mode Analytics SQL Tutorial", credibility: "Mode Analytics" },
  "aws": { name: "AWS", timeframe: "8-12 weeks", resource: "AWS Solutions Architect Associate", credibility: "Amazon Web Services" },
  "machine learning": { name: "Machine Learning", timeframe: "10-14 weeks", resource: "Andrew Ng's ML Specialization", credibility: "Stanford / Coursera" },
  "project management": { name: "Project Management", timeframe: "6-8 weeks", resource: "Google Project Management Certificate", credibility: "Google Career Certificates" },
  "data analysis": { name: "Data Analysis", timeframe: "4-6 weeks", resource: "Google Data Analytics Certificate", credibility: "Google Career Certificates" },
  "agile": { name: "Agile / Scrum", timeframe: "2-4 weeks", resource: "Certified ScrumMaster (CSM)", credibility: "Scrum Alliance" },
  "product management": { name: "Product Management", timeframe: "6-8 weeks", resource: "Product School PM Certificate", credibility: "Product School" },
  "cloud": { name: "Cloud Computing", timeframe: "8-12 weeks", resource: "Google Cloud Professional Certificate", credibility: "Google Cloud" },
  "kubernetes": { name: "Kubernetes", timeframe: "4-6 weeks", resource: "Certified Kubernetes Admin (CKA)", credibility: "CNCF" },
  "react": { name: "React", timeframe: "4-6 weeks", resource: "Meta Front-End Developer Certificate", credibility: "Meta" },
  "leadership": { name: "Leadership", timeframe: "6-8 weeks", resource: "Wharton Executive Leadership", credibility: "Wharton / Coursera" },
  "communication": { name: "Communication", timeframe: "3-4 weeks", resource: "High-Impact Business Writing", credibility: "University of Colorado" },
  "analytics": { name: "Analytics", timeframe: "4-6 weeks", resource: "Tableau Desktop Specialist", credibility: "Tableau / Salesforce" },
  "six sigma": { name: "Six Sigma", timeframe: "6-8 weeks", resource: "Lean Six Sigma Green Belt", credibility: "ASQ" },
  "sales": { name: "Sales", timeframe: "4-6 weeks", resource: "Salesforce Sales Development", credibility: "Salesforce / Trailhead" },
  "marketing": { name: "Digital Marketing", timeframe: "4-6 weeks", resource: "Google Digital Marketing Certificate", credibility: "Google Career Certificates" },
  "excel": { name: "Advanced Excel", timeframe: "2-3 weeks", resource: "Excel Skills for Business Specialization", credibility: "Macquarie University" },
  "financial modeling": { name: "Financial Modeling", timeframe: "6-8 weeks", resource: "FMVA Certification", credibility: "Corporate Finance Institute" },
  "compliance": { name: "Compliance", timeframe: "4-6 weeks", resource: "Certified Compliance & Ethics Professional", credibility: "SCCE" },
  "stakeholder management": { name: "Stakeholder Management", timeframe: "3-4 weeks", resource: "PMI Stakeholder Engagement", credibility: "PMI" },
  "cross-functional": { name: "Cross-functional Leadership", timeframe: "4-6 weeks", resource: "Leading Teams Specialization", credibility: "University of Michigan" },
  "strategic planning": { name: "Strategic Planning", timeframe: "6-8 weeks", resource: "Business Strategy Specialization", credibility: "University of Virginia / Darden" },
};

export const HR_TIPS = {
  personal: [
    { speaker: "Laszlo Bock, Google SVP People Ops", tip: "Your resume is a marketing document, not your autobiography. Every line should sell. If it doesn't prove you can do THIS job, delete it." },
    { speaker: "Lou Adler, Performance-based Hiring", tip: "A summary that says 'results-oriented professional' tells me nothing. Show me the biggest thing you've ever accomplished in one sentence. That's your summary." },
    { speaker: "Google Recruiters", tip: "We spend 7.4 seconds on initial scan. Your name, current title, and top accomplishment must be visible without scrolling. Everything else is a maybe." },
    { speaker: "Laszlo Bock", tip: "58% of resumes have typos. One typo and you're in the reject pile. Not because we're pedantic — because attention to detail IS the job." },
  ],
  experience: [
    { speaker: "Laszlo Bock, Google", tip: "Use the X-Y-Z formula: 'Accomplished [X] as measured by [Y], by doing [Z].' Not 'Responsible for managing a team.' That tells me nothing about impact." },
    { speaker: "Ex-Goldman Sachs Recruiter", tip: "If your bullet doesn't have a number, it's an opinion. '$4.2M revenue increase' is a fact. 'Significantly improved sales' is fiction." },
    { speaker: "McKinsey Hiring Partner", tip: "We look for: Did you LEAD or PARTICIPATE? 'Led a team of 12 to deliver...' beats 'Was part of a team that...' every single time. Own the verb." },
    { speaker: "Amazon Bar Raiser", tip: "I read your most recent role first. If the bullets are weak there, I never make it to the rest. Front-load your strongest impact." },
    { speaker: "Laszlo Bock", tip: "Remove everything from more than 15 years ago unless it's extraordinary. Nobody cares about your 2005 internship." },
  ],
  skills: [
    { speaker: "Google Technical Recruiter", tip: "Don't list skills you can't be tested on in an interview. If 'Python' is on your resume and you can't reverse a linked list, that's a fail." },
    { speaker: "LinkedIn Data, 2024", tip: "ATS systems scan your Skills section separately from experience. A skill in your bullets but not your Skills list = invisible to the algorithm." },
    { speaker: "Ex-McKinsey Partner", tip: "Skills like 'Microsoft Office' and 'Communication' are noise. Everyone has them. List what separates you: specific tools, frameworks, certifications." },
  ],
  education: [
    { speaker: "Goldman Sachs Campus Recruiting", tip: "If you graduated more than 5 years ago, your GPA doesn't matter. Move education below experience. Your work proves you now." },
    { speaker: "Laszlo Bock", tip: "After your first job, where you went to school matters less than what you've done. Google found zero correlation between school prestige and job performance." },
  ],
  training: [
    { speaker: "SHRM Research, 2024", tip: "Certifications that match the JD's exact wording increase callback rates by 31%. Don't list 'PMP' if the JD says 'Project Management Professional' — spell it out AND abbreviate." },
    { speaker: "Fortune 500 CHRO", tip: "A certification from 2015 without renewal is a red flag. Either it's current or remove it. Stale credentials suggest you've stopped growing." },
  ],
};

export const WINNING_BULLETS = {
  faang: [
    { pattern: "Architected [system] serving [X]M+ daily active users, reducing p99 latency by [Y]% through [technique].", context: "Engineering / SRE" },
    { pattern: "Led cross-functional team of [X] engineers to deliver [product] [Y] weeks ahead of schedule, directly enabling $[Z]M ARR.", context: "Tech Lead / EM" },
    { pattern: "Designed and shipped [feature] achieving [X]% adoption in first [Y] weeks, contributing [Z]% lift in core engagement metric.", context: "Product / Growth" },
    { pattern: "Reduced infrastructure costs by $[X]M/year by migrating [Y] services to [cloud/k8s], maintaining 99.99% uptime.", context: "DevOps / Cloud" },
    { pattern: "Spearheaded A/B testing framework used by [X]+ teams; experiments driven by this system generated $[Y]M incremental revenue.", context: "Data / Experimentation" },
    { pattern: "Mentored [X] junior engineers, [Y] of whom were promoted within [Z] months — highest conversion rate on the org.", context: "Leadership" },
  ],
  mbb: [
    { pattern: "Led [X]-person engagement for Fortune 500 client, identifying $[Y]M in operational savings through MECE-structured diagnostic.", context: "Strategy Consulting" },
    { pattern: "Developed market-entry strategy for [industry] client, resulting in [X]% first-year market share in $[Y]B addressable market.", context: "Market Entry" },
    { pattern: "Built financial model forecasting [X]-year P&L scenarios; board adopted recommended growth path yielding [Y]% ROIC.", context: "Corporate Finance" },
    { pattern: "Synthesized [X]+ stakeholder interviews into executive recommendation deck adopted by C-suite within [Y] days of presentation.", context: "Executive Advisory" },
    { pattern: "Managed due diligence workstream for $[X]M acquisition, uncovering [Y]% cost synergy opportunity missed by initial assessment.", context: "M&A / Due Diligence" },
  ],
  finance: [
    { pattern: "Executed [X]+ trades valued at $[Y]M+, generating [Z]bps alpha above benchmark through proprietary quantitative signals.", context: "Trading / Portfolio" },
    { pattern: "Built DCF and LBO models for $[X]B+ deal pipeline; [Y] of [Z] pitched deals reached signed LOI.", context: "Investment Banking" },
    { pattern: "Managed $[X]M portfolio delivering [Y]% annualized returns, outperforming index by [Z]bps over [N]-year period.", context: "Asset Management" },
    { pattern: "Reduced regulatory findings by [X]% YoY through implementation of automated compliance monitoring across [Y] business lines.", context: "Compliance / Risk" },
    { pattern: "Streamlined month-end close from [X] to [Y] days, eliminating [Z] manual reconciliations through process automation.", context: "FP&A / Accounting" },
  ],
  executive: [
    { pattern: "Grew division from $[X]M to $[Y]M revenue over [Z] years, achieving [N]% CAGR while expanding margin by [M]pp.", context: "P&L Leadership" },
    { pattern: "Led transformation of [X]-person organization, achieving [Y]% employee engagement improvement and [Z]% voluntary attrition reduction.", context: "Organizational Change" },
    { pattern: "Presented quarterly strategy updates to Board of Directors; secured approval for $[X]M capital investment in [initiative].", context: "Board Relations" },
    { pattern: "Negotiated [X] strategic partnerships collectively valued at $[Y]M, opening [Z] new market segments.", context: "Business Development" },
    { pattern: "Recruited and developed leadership bench of [X] direct reports, [Y] of whom advanced to VP+ within [Z] years.", context: "Talent Development" },
  ],
  startup: [
    { pattern: "Scaled company from [X] to [Y] employees and $[Z]M ARR in [N] months; raised Series [A/B] at $[M]M valuation.", context: "Founder / CEO" },
    { pattern: "Designed go-to-market strategy achieving [X] paying customers in first [Y] months with $[Z] CAC, [N]x below industry avg.", context: "GTM / Growth" },
    { pattern: "Built MVP in [X] weeks that validated core hypothesis; pivoted [Y] times before finding PMF at [Z]% MoM growth.", context: "Product / Technical Founder" },
    { pattern: "Established advisory board of [X] industry leaders; leveraged network to close [Y] enterprise pilots worth $[Z]M TCV.", context: "Founder / BD" },
  ],
  product: [
    { pattern: "Defined and launched [product/feature] generating $[X]M incremental revenue; achieved [Y]% DAU adoption within [Z] weeks.", context: "Product Launch" },
    { pattern: "Prioritized roadmap using RICE framework across [X] competing initiatives; delivered [Y]% improvement in core North Star metric.", context: "Roadmap / Prioritization" },
    { pattern: "Ran [X] user research sessions and [Y] A/B experiments, increasing conversion from [Z]% to [N]% (+[M]pp lift).", context: "User Research / Experimentation" },
    { pattern: "Collaborated with [X]-person engineering squad to reduce feature delivery cycle from [Y] to [Z] weeks through agile refinements.", context: "Agile / Delivery" },
    { pattern: "Owned OKRs for [X] product area ($[Y]M revenue line); exceeded targets by [Z]% for [N] consecutive quarters.", context: "OKR / Metrics Ownership" },
  ],
  marketing: [
    { pattern: "Grew organic traffic from [X]K to [Y]K monthly sessions in [Z] months, reducing paid CAC by [N]%.", context: "SEO / Content" },
    { pattern: "Launched multi-channel campaign generating [X]K qualified leads at $[Y] CPL — [Z]% below industry benchmark.", context: "Demand Gen" },
    { pattern: "Built personal brand to [X]K+ followers across [Y] platforms, converting [Z]% into paid community/product customers.", context: "Personal Branding" },
    { pattern: "Managed $[X]M annual marketing budget across [Y] channels, achieving [Z]:1 blended ROAS.", context: "Marketing Leadership" },
    { pattern: "Created content engine producing [X] pieces/month; [Y] went viral (100K+ views), driving [Z]% of annual pipeline.", context: "Content Marketing" },
  ],
  operations: [
    { pattern: "Reduced operational costs by $[X]M annually through Lean Six Sigma process redesign across [Y] facilities.", context: "Process Improvement" },
    { pattern: "Managed supply chain for [X] SKUs across [Y] geographies, reducing lead time by [Z]% while maintaining [N]% fill rate.", context: "Supply Chain" },
    { pattern: "Implemented ERP system ([SAP/Oracle]) across [X] business units, completing [Y] months ahead of schedule and $[Z]M under budget.", context: "Systems / ERP" },
    { pattern: "Led [X]-person operations team through [Y]% volume increase, maintaining [Z]% quality score and [N]% on-time delivery.", context: "Operations Management" },
    { pattern: "Developed SOPs for [X] critical processes, reducing error rate from [Y]% to [Z]% and saving [N] hours/week.", context: "Process Documentation" },
  ],
  sales: [
    { pattern: "Exceeded quota by [X]% ($[Y]M) in [Z] consecutive quarters, ranking #[N] of [M] enterprise AEs globally.", context: "Enterprise Sales" },
    { pattern: "Built and led [X]-person SDR team generating [Y]+ qualified opportunities/month with $[Z]M average deal size.", context: "Sales Leadership" },
    { pattern: "Closed $[X]M in new logo business, including [Y] Fortune 500 accounts, with average sales cycle of [Z] days.", context: "New Business" },
    { pattern: "Increased account expansion revenue by [X]% ($[Y]M) through structured QBR program across [Z] strategic accounts.", context: "Account Management" },
    { pattern: "Implemented [CRM/methodology] across [X]-person sales org, improving win rate from [Y]% to [Z]% within [N] quarters.", context: "Sales Operations" },
  ],
};

export const SEMANTIC_PIVOTS = {
  "frontend-frameworks":  ["react", "vue", "angular", "svelte", "next.js", "nuxt", "ember", "preact", "solid"],
  "backend-frameworks":   ["node", "express", "django", "flask", "fastapi", "spring", "rails", "laravel", "nestjs", "asp.net"],
  "programming-langs":    ["python", "javascript", "typescript", "java", "c#", "go", "rust", "ruby", "php", "kotlin", "swift"],
  "cloud-platforms":      ["aws", "azure", "gcp", "google cloud", "cloud", "heroku", "digitalocean", "vercel"],
  "data-tools":           ["sql", "mysql", "postgresql", "mongodb", "redis", "dynamodb", "cassandra", "elasticsearch", "snowflake", "bigquery", "redshift"],
  "bi-analytics":         ["tableau", "power bi", "looker", "data studio", "metabase", "quicksight", "analytics", "data visualization"],
  "ml-ai":                ["machine learning", "deep learning", "ai", "artificial intelligence", "nlp", "computer vision", "tensorflow", "pytorch", "scikit-learn", "llm"],
  "devops-infra":         ["docker", "kubernetes", "terraform", "ansible", "ci/cd", "jenkins", "github actions", "gitlab ci", "devops", "infrastructure as code"],
  "project-mgmt":         ["agile", "scrum", "kanban", "jira", "asana", "trello", "project management", "program management", "waterfall", "safe"],
  "crm-sales":            ["salesforce", "hubspot", "crm", "pipedrive", "zoho", "dynamics 365", "sales operations", "business development"],
  "marketing-digital":    ["seo", "sem", "digital marketing", "content marketing", "google analytics", "social media", "ppc", "email marketing", "content strategy", "growth marketing"],
  "design-ux":            ["figma", "sketch", "adobe xd", "user research", "wireframing", "prototyping", "ux", "ui design", "design thinking", "usability testing"],
  "leadership-mgmt":      ["team lead", "people management", "coaching", "mentoring", "strategic planning", "stakeholder management", "cross-functional", "executive leadership", "change management"],
  "finance-ops":          ["p&l", "revenue", "budget", "financial modeling", "forecasting", "operations", "supply chain", "lean", "six sigma", "process improvement"],
  "compliance-risk":      ["compliance", "risk management", "audit", "regulatory", "gdpr", "sox", "hipaa", "data privacy", "governance", "information security"],
  "testing-qa":           ["a/b testing", "unit testing", "qa", "test automation", "selenium", "cypress", "jest", "testing", "quality assurance"],
  "communication":        ["communication", "presentation", "negotiation", "public speaking", "storytelling", "technical writing", "client relationship"],
};

export const COMMON_MISSPELLINGS = {
  "managment": "management", "managemnet": "management", "responsable": "responsible",
  "responsibilites": "responsibilities", "responsibilties": "responsibilities",
  "achived": "achieved", "acheived": "achieved", "acheive": "achieve",
  "developement": "development", "devlopment": "development", "develope": "develop",
  "enviroment": "environment", "enviorment": "environment",
  "recieved": "received", "occured": "occurred", "occurence": "occurrence",
  "accomodate": "accommodate", "acommodate": "accommodate",
  "seperate": "separate", "definately": "definitely", "definitly": "definitely",
  "occassion": "occasion", "occassionally": "occasionally",
  "succesful": "successful", "successfull": "successful",
  "professionnal": "professional", "proffessional": "professional",
  "experiance": "experience", "experince": "experience",
  "comunication": "communication", "communcation": "communication",
  "knowlege": "knowledge", "knowledgable": "knowledgeable",
  "liason": "liaison", "liaision": "liaison",
  "maintainance": "maintenance", "maintanence": "maintenance",
  "neccessary": "necessary", "neccesary": "necessary",
  "priviledge": "privilege", "privelege": "privilege",
  "reccommend": "recommend", "recomend": "recommend",
  "strengh": "strength", "strentgh": "strength",
  "throught": "through", "thoughout": "throughout",
  "untill": "until", "begining": "beginning",
  "bussiness": "business", "busines": "business",
  "calender": "calendar", "catagory": "category",
  "commited": "committed", "committment": "commitment",
  "completly": "completely", "concious": "conscious",
  "consistant": "consistent", "currenly": "currently",
  "discription": "description", "efficent": "efficient",
  "excercise": "exercise", "existance": "existence",
  "foriegn": "foreign", "fulfil": "fulfill",
  "goverment": "government", "grammer": "grammar",
  "guarentee": "guarantee", "immediatly": "immediately",
  "independant": "independent", "indispensible": "indispensable",
  "intergrate": "integrate", "judgement": "judgment",
  "laguage": "language", "lenght": "length",
  "liase": "liaise", "manouvre": "maneuver",
  "millenium": "millennium", "mispell": "misspell",
  "noticable": "noticeable", "paralell": "parallel",
  "persistant": "persistent", "personel": "personnel",
  "posession": "possession", "prefered": "preferred",
  "publically": "publicly", "pursuade": "persuade",
  "questionaire": "questionnaire", "refered": "referred",
  "relevent": "relevant", "rythm": "rhythm",
  "seige": "siege", "shedule": "schedule",
  "supercede": "supersede", "surprize": "surprise",
  "tommorow": "tomorrow", "wierd": "weird",
  "yeild": "yield", "analisis": "analysis",
  "analize": "analyze", "budgetting": "budgeting",
  "colaboration": "collaboration", "collabaration": "collaboration",
  "effeciency": "efficiency", "implmented": "implemented",
  "implmentation": "implementation", "infastructure": "infrastructure",
  "intergration": "integration", "optmization": "optimization",
  "organzation": "organization", "performace": "performance",
  "strategize": "strategize", "technolgy": "technology",
};

export const CONFUSABLES = [
  { rx: /\btheir\s+(is|was|are|were|has|have|will|can|should|would)\b/gi, word: "their", fix: "there", type: "grammar", tip: "\"Their\" is possessive. Use \"there\" before a verb." },
  { rx: /\bthere\s+(car|team|company|project|plan|manager|work|resume|experience|role|skills?|goals?)\b/gi, word: "there", fix: "their", type: "grammar", tip: "\"There\" refers to a place. Use \"their\" for possession." },
  { rx: /\byour\s+(a|an|the|going|doing|working|welcome|right|wrong|hired|fired)\b/gi, word: "your", fix: "you're", type: "grammar", tip: "\"Your\" is possessive. Use \"you're\" (you are)." },
  { rx: /\bits\s+(a|an|the|very|not|been|going|important|clear|time)\b/gi, word: "its", fix: "it's", type: "grammar", tip: "\"Its\" is possessive. Use \"it's\" (it is) before adjectives/articles." },
  { rx: /\bit's\s+(own|self|purpose|value|function|role|features?)\b/gi, word: "it's", fix: "its", type: "grammar", tip: "\"It's\" means \"it is\". Use \"its\" for possession." },
  { rx: /\beffect\b(?=\s+(the|a|an|change|improvement|growth))/gi, word: "effect", fix: "affect", type: "grammar", tip: "\"Effect\" is usually a noun. Use \"affect\" as a verb." },
  { rx: /\bthen\b(?=\s+(I|we|they|he|she|it|the|a)\s+(was|were|are|is))/gi, word: "then", fix: "than", type: "grammar", tip: "Use \"than\" for comparisons, \"then\" for sequence." },
  { rx: /\blose\b(?=\s+(fitting|cannon))/gi, word: "lose", fix: "loose", type: "grammar", tip: "\"Lose\" means to misplace. \"Loose\" means not tight." },
];

export const PASSIVE_RX = /\b(was|were|is|are|been|being)\s+(achieved|managed|developed|created|designed|implemented|built|led|driven|launched|delivered|completed|increased|decreased|reduced|improved|generated|established|organized|maintained|coordinated|facilitated|executed|analyzed|evaluated|performed|prepared|processed|produced|provided|resolved|reviewed|scheduled|supervised|supported|trained|updated|utilized|written|handled|conducted|monitored|operated|planned|presented|assisted|contributed|demonstrated)\b/gi;

export const WEAK_PHRASES = [
  { rx: /\bresponsible for\b/gi, fix: "Led", tip: "\"Responsible for\" is passive. Start with an action verb.", type: "style" },
  { rx: /\bhelped (to |with )?/gi, fix: "Facilitated ", tip: "\"Helped\" is vague. Use a specific action verb.", type: "style" },
  { rx: /\bworked on\b/gi, fix: "Developed", tip: "\"Worked on\" lacks impact. Be specific about what you did.", type: "style" },
  { rx: /\bwas involved in\b/gi, fix: "Contributed to", tip: "\"Was involved in\" is vague and passive.", type: "style" },
  { rx: /\bdealt with\b/gi, fix: "Managed", tip: "\"Dealt with\" is informal for a resume.", type: "style" },
  { rx: /\bin charge of\b/gi, fix: "Directed", tip: "\"In charge of\" is wordy. Use a direct verb.", type: "style" },
  { rx: /\bduties included\b/gi, fix: "Key accomplishments:", tip: "Focus on accomplishments, not duties.", type: "style" },
  { rx: /\btasked with\b/gi, fix: "Spearheaded", tip: "\"Tasked with\" is passive. Own the action.", type: "style" },
  { rx: /\bsuccessfully\b/gi, fix: "(remove)", tip: "\"Successfully\" is filler — your results should speak for themselves.", type: "filler" },
  { rx: /\bvarious\b/gi, fix: "(be specific)", tip: "\"Various\" is vague. Quantify: how many? which ones?", type: "filler" },
  { rx: /\betc\.?\b/gi, fix: "(list them)", tip: "\"Etc.\" weakens your claim. List the actual items.", type: "filler" },
  { rx: /\ba lot of\b/gi, fix: "(quantify)", tip: "\"A lot of\" is informal. Use specific numbers.", type: "filler" },
  { rx: /\bteam player\b/gi, fix: "cross-functional collaborator", tip: "\"Team player\" is cliche. Show collaboration with specifics.", type: "style" },
  { rx: /\bhard worker\b/gi, fix: "(show results instead)", tip: "\"Hard worker\" is subjective. Demonstrate through metrics.", type: "style" },
  { rx: /\bgo-getter\b/gi, fix: "(show initiative instead)", tip: "\"Go-getter\" is a cliche. Show initiative through examples.", type: "style" },
  { rx: /\bself-starter\b/gi, fix: "autonomous leader", tip: "\"Self-starter\" is overused. Reframe as ownership.", type: "style" },
  { rx: /\bthink outside the box\b/gi, fix: "innovative problem-solver", tip: "Avoid cliches — use specific examples of creativity.", type: "style" },
  { rx: /\bsynergy\b/gi, fix: "collaboration", tip: "\"Synergy\" is corporate jargon. Use plain language.", type: "style" },
  { rx: /\bleveraged?\b/gi, fix: "used", tip: "\"Leverage\" is overused in resumes. Consider simpler alternatives.", type: "style" },
  { rx: /\butilized?\b/gi, fix: "used", tip: "\"Utilize\" is unnecessarily complex. \"Used\" is clearer.", type: "style" },
];

export const BUZZWORDS = [
  { rx: /\bpassionate about\b/gi, tip: "\"Passionate about\" is subjective fluff. Show passion through what you built or achieved." },
  { rx: /\bpassionate\b/gi, tip: "\"Passionate\" is unverifiable. Replace with a concrete result that proves it." },
  { rx: /\bmotivated\b/gi, tip: "\"Motivated\" tells, doesn't show. Demonstrate motivation through outcomes." },
  { rx: /\bdetail[- ]oriented\b/gi, tip: "\"Detail-oriented\" is the #1 most overused resume adjective. Prove it with a specific example." },
  { rx: /\bresults[- ]driven\b/gi, tip: "\"Results-driven\" is meaningless without... results. Add the numbers." },
  { rx: /\bexcellent communication\b/gi, tip: "Everyone claims \"excellent communication.\" Show it: presentations given, docs authored, teams aligned." },
  { rx: /\bstrong work ethic\b/gi, tip: "\"Strong work ethic\" is invisible to ATS. Replace with measurable output." },
  { rx: /\bproven track record\b/gi, tip: "\"Proven track record\" — then prove it! Add specific numbers and outcomes." },
  { rx: /\bstrategic thinker\b/gi, tip: "\"Strategic thinker\" is a self-assessment. Show strategy through decisions and their outcomes." },
  { rx: /\binnovative\b/gi, tip: "\"Innovative\" is a claim. Describe the innovation: what you created and its impact." },
  { rx: /\bdynamic\b/gi, tip: "\"Dynamic\" is resume noise. Replace with what you actually did." },
  { rx: /\bproactive\b/gi, tip: "\"Proactive\" — show it! Describe what you initiated before being asked." },
  { rx: /\bexceptional\b/gi, tip: "\"Exceptional\" is self-awarded. Let your metrics speak instead." },
];

export const GRAMMAR_RULES = [
  { rx: /\bi\b/g, fix: "I", type: "grammar", tip: "The pronoun \"I\" should always be capitalized." },
  { rx: /\s{2,}/g, fix: " ", type: "formatting", tip: "Remove extra spaces." },
  { rx: /\.\./g, fix: ".", type: "formatting", tip: "Double period detected." },
  { rx: /,,/g, fix: ",", type: "formatting", tip: "Double comma detected." },
  { rx: /\b(alot)\b/gi, fix: "a lot", type: "grammar", tip: "\"Alot\" is not a word. Use \"a lot\" (two words)." },
  { rx: /\b(could of|would of|should of)\b/gi, fix: (m) => m.replace(" of", " have"), type: "grammar", tip: "Use \"could have\", not \"could of\"." },
  { rx: /\b(irregardless)\b/gi, fix: "regardless", type: "grammar", tip: "\"Irregardless\" is non-standard. Use \"regardless\"." },
  { rx: /\b(supposably)\b/gi, fix: "supposedly", type: "grammar", tip: "\"Supposably\" is a common error. Use \"supposedly\"." },
  { rx: /\b(per say)\b/gi, fix: "per se", type: "grammar", tip: "The Latin phrase is \"per se\", not \"per say\"." },
  { rx: /\b(for all intensive purposes)\b/gi, fix: "for all intents and purposes", type: "grammar", tip: "The correct phrase is \"for all intents and purposes\"." },
];
